name: Run Generator
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      commit:
        description: 'Save Output of Generator'
        required: true
        default: true
        type: boolean

jobs:
  run_generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install Node
        uses: actions/setup-node@v4

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: test-github-connect
          region: us-east-1
          

      - name: Install Dependencies
        run: npm ci
      - name: Run Generator
        run: |
          npm run generator
          npm run prettier

      - name: Git Status
        id: git-status
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "CHANGES=true" >> "$GITHUB_OUTPUT"
          else
            echo "CHANGES=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit Changes
        if: steps.git-status.outputs.CHANGES == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "pwed@duck.com"
          git checkout -B generator/updates
          git add .
          git commit -m "Generator Updates"
          git push
      
      - name: Create PR
        run: |
          gh pr create -B main -H generator/updates --title 'Merge generator/updates into main' --body 'Created by Github action'
          gh pr merge --auto --delete-branch --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}